#!/usr/bin/env bash
# Sources used to maintain Jenny92's PortMaster release from upstream stable.

PORTMASTER_GITHUB_WEB_ORIGIN="${PORTMASTER_GITHUB_WEB_ORIGIN:-https://github.com}"
JENNY92_PORTMASTER_GUI_REPOSITORY="${JENNY92_PORTMASTER_GUI_REPOSITORY:-jenny92-tech/PortMaster-GUI}"
PORTMASTER_UPSTREAM_REPOSITORY="${PORTMASTER_UPSTREAM_REPOSITORY:-PortsMaster/PortMaster-GUI}"

JENNY92_PORTMASTER_GUI_RELEASES_URL="${JENNY92_PORTMASTER_GUI_RELEASES_URL:-$PORTMASTER_GITHUB_WEB_ORIGIN/$JENNY92_PORTMASTER_GUI_REPOSITORY/releases}"
JENNY92_PORTMASTER_GUI_RELEASE_ASSET_BASE="${JENNY92_PORTMASTER_GUI_RELEASE_ASSET_BASE:-$JENNY92_PORTMASTER_GUI_RELEASES_URL/download}"
PORTMASTER_UPSTREAM_RELEASES_URL="${PORTMASTER_UPSTREAM_RELEASES_URL:-$PORTMASTER_GITHUB_WEB_ORIGIN/$PORTMASTER_UPSTREAM_REPOSITORY/releases}"
PORTMASTER_UPSTREAM_VERSION_URL="${PORTMASTER_UPSTREAM_VERSION_URL:-$PORTMASTER_UPSTREAM_RELEASES_URL/latest/download/version.json}"
PORTMASTER_UPSTREAM_GIT_URL="${PORTMASTER_UPSTREAM_GIT_URL:-$PORTMASTER_GITHUB_WEB_ORIGIN/$PORTMASTER_UPSTREAM_REPOSITORY.git}"
